# Generated by Django 5.0.1 on 2024-01-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dish',
            table='caidan',
        ),
    ]
